# https://github.com/n3wt0n/ReusableWorkflow/blob/f89362e4c298f42a89be625eee44c5e85bd8166b/.github/workflows/buildAndPublishDockerImage.yml#L3-L4
# https://github.com/n3wt0n/ActionsTest/blob/fe32f39d831d08c84fec078f6aa912f6fd606568/.github/workflows/reusableWorkflowsUser.yml
name: BuildAndPushImageOnHarbor
on:
  workflow_call:
    inputs:
      run_number:
        description: 'The run number of the workflow'
        required: true
        type: string
      registry:      
        description: 'The registry to push the image to'
        required: true
        type: string
      IMAGE_NAME:
        description: 'The registry to push the image to'
        required: true
        type: string
      PROJECT:
         required: true
         type: string
    secrets:
      username:
         required: true         
      password:
         required: true
         
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        registry: $REGISTRY
        username: ${{ secrets.username  }}
        password: ${{ secrets.password }}

    - uses: actions/checkout@v3
    - name: BuildAndPushImageOnHarbor
      run: |
        pwd
        docker buildx build --file ./dockerfile --platform linux/arm64 --tag ${{ inputs.REGISTRY }}/karsoekube/arm-guids:${{ inputs.run_number }} --push .
        # docker push ${{ inputs.REGISTRY }}/karsoekube/arm-guids:${{ inputs.run_number }}
    - name: Clone Repository
      run: |
        git clone https://${{ inputs.TOKEN}}@${{ inputs.REPOSITORY }}

    - name: UpdateRefFile
      run: |
        echo "${{ inputs.run_number }}"> ./picluster/apps/${{ inputs.PROJECT }}/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}.imageref.txt
        
    - name: Push to Repo
      run: |
        git config --global user.name "${{secrets.USERNAME_GITHUB}}"
        git config --global user.email "${{secrets.EMAIL_GITHUB}}"
        cd ./picluster
        git add .
        git commit -m "Updated by GitHub Actions"
        git push https://${{ secrets.TOKEN}}@${{ inputs.REPOSITORY }} --all
